title: 阿金的博客
remote_theme: curatorjin/Furendo
description: _(:з」∠)_
signature: 早起赶画稿，熬夜写项目
nick_name: 阿金
nick_name_vcard: curatorjin
email: disciple_sneaker@163.com
baseurl: "/blog"
gems: [jekyll-feed, jekyll-seo-tag, jekyll-paginate]
paginate: 7
paginate_path: "/page:num/"
friends:
    - name: Neei的笔记库
      link: https://www.yuque.com/aaneeini?tab=books    
    - name: 叶子的博客
      link: http://leafw.cn/